# Generated by Django 4.1.1 on 2022-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0006_alter_application_client_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True, help_text="List of allowed redirect URIs to follow after an OIDC RP-initiated logout, space separated"
            ),
        ),
    ]
